import { Plan } from '@/types/types';

export const plans: Plan[] = [
    {
        id: 'monthly',
        name: 'Monthly',
        price: 499,
        duration: 'month',
        description: 'Perfect for trying out our premium features',
        features: [
            'Voice-controlled note creation',
            'Unlimited notes storage',
            'Cross-device synchronization',
            'Voice commands customization',
            '5GB cloud storage',
        ],
        stripePriceId: 'price_1RPNpeLpUOMFS1MrowS5zdZ5',
    },
    {
        id: 'quarterly',
        name: 'Quarterly',
        price: 1349,
        duration: '3 months',
        description: 'Our most flexible premium option',
        features: [
            'Voice-controlled note creation',
            'Unlimited notes storage',
            'Cross-device synchronization',
            'Voice commands customization',
            '15GB cloud storage',
            'Priority customer support',
        ],
        savePercent: 17,
        stripePriceId: 'price_1RPNpeLpUOMFS1MrIVGrKBba',
    },
    {
        id: 'biannual',
        name: '6 Months',
        price: 2499,
        duration: '6 months',
        description: 'Great value for committed users',
        features: [
            'Voice-controlled note creation',
            'Unlimited notes storage',
            'Cross-device synchronization',
            'Voice commands customization',
            '25GB cloud storage',
            'Priority customer support',
            'Advanced analytics',
        ],
        popular: true,
        savePercent: 25,
        stripePriceId: 'price_1RPNpeLpUOMFS1Mr9fYLVsRu',
    },
    {
        id: 'annual',
        name: 'Annual',
        price: 4999,
        duration: 'year',
        description: 'Best value for our loyal users',
        features: [
            'Voice-controlled note creation',
            'Unlimited notes storage',
            'Cross-device synchronization',
            'Voice commands customization',
            '50GB cloud storage',
            'Premium customer support',
            'Advanced analytics',
            'Early access to new features',
        ],
        savePercent: 33,
        stripePriceId: 'price_1RPNpeLpUOMFS1Mr02jBCFZg',
    },
];
